### ISSUE TITLE
Accessing a different environment variable locally

### ISSUE THREAD

**Issue by Madhu-gangumolu** [eschweitzer78/lwrjs-env-module-provider#1]
**Got Answer from (Emmanuel Schweitzer)**

I changed the app code as follows:
$ more src/modules/example/app/app.js

import { LightningElement } from 'lwc';

import envValue from '@eschweitzer78/env/EXAMPLE';

export default class HelloWorldApp extends LightningElement {

  get username() { return envValue; }

}

src/modules/example/app/app.js (END)

I then went on and added the EXAMPLE variable in the .env file at the root of my sample project as required when running heroku local:
$ more .env

PORT=3456

USERNAME=Some funky name

EXAMPLE=It works!

.env (END)

I finally ran the app locally (pruned for brevity):
$ heroku local

[OKAY] Loaded ENV .env File as KEY=VALUE Format

8:17:39 am web.1 |  > lwr-project@0.0.1 start

8:17:39 am web.1 |  > lwr serve --mode prod

8:17:40 am web.1 |  LOG_LEVEL: info

8:17:40 am web.1 |  > ctor { port: undefined, serverMode: 'prod' }

8:17:40 am web.1 |  < ctor {

8:17:40 am web.1 |    port: 3456,

8:17:40 am web.1 |    ignoreLwrConfigFile: false,

8:17:40 am web.1 |    lwrConfigFile: '$rootDir/lwr.config.json',

8:17:40 am web.1 |    basePath: '',

The app then works as expected:

![image](https://user-images.githubusercontent.com/105501962/183010542-2c636e6d-e732-47c2-a0b9-e0df376da9bd.png)

**Comment by Madhu-gangumolu** [comment]
For **heroku local** command it works fine can you try with **npm run start** command it will throw an error **500 - Error retrieving view for route "example"**

**Comment by eschweitzer78** [comment]
Hi,

`heroku local` takes environment variables from a .env file.

However if you use `npm run start`, you need a real environment variable, so please try
`export EXAMPLE=Madhu`
in the shell (or whichever variation works in your current shell) before `npm run start`

If you run this in a docker image, do not forget to use the `-e` option when using `docker run` to create an environment variable within the image.

**Comment by Madhu-gangumolu** [comment]
Sorry sir I didn't get that. Where we need to run export EXAMPLE=Madhu. If it is in powershell I'm getting this error
![image](https://user-images.githubusercontent.com/105501962/183058909-f7178f39-90ab-4e1e-95e7-b2febc9742bd.png)

**Comment by eschweitzer78** [comment]
Please pick the syntax that works in the shell tool you're using (export is for UNIX zsh and similar). See the [powershell doco](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.2) if that's what you're using. Apologies but I can't help you on Windows...
